name: Deploy api
#on:
#  push:
#    branches: [main]
on:
  push:
    branches: [ ci/add_ci_for_cheekapp ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            cd /home/gcoue/cheek-static/
            git pull origin master
            git status
            npm install --only=prod
            pm2 restart node1